name: llamante
on:
  push:
    branches:
      - main
jobs:
  call-install-node:
    uses: .github/workflows/install-node.yml@main
    with:
      username: "JORGE"
  call-execute-command:
    uses: .github/workflows/command.yml@main
