name: llamante
on:
  push:
    branches:
      - main
jobs:
  call-install-node:
    uses: ./.github/workflows/install-node.yml
    with:
      username: ${{ secrets.GIT_TOKEN }}
  call-execute-command:
    uses: ./.github/workflows/command.yml
