name: reutilizar
on:
  workflow_call:
    inputs:
      npmkey:
        description: Token de npm para publicar paquetes
        default: ${{ secret.NPM_TOKEN }}
        required: false
        type: string
jobs:
  show-token:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrando el key secret
        run: echo esto es mi valor ${{inputs.npmkey}}