name: reutilizar
on:
  workflow_call:
    inputs:
      username:
        description: 'Permite mostrr el nombre de un usuario'
        default: 'N\A'
        required: false
        type: string
jobs:
  print-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clonando un repository
        run: git clone ${{ inputs.username }}
