name: reutilizar
on:
  workflow_call:
    inputs:
      reponame:
        description: Nombre del repositorio que necesitamos clonar
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
jobs:
  clone_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Clonando un repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.reponame }}
          ref: master
          token: ${{ secrets.GIT_TOKEN }}
      - name: Que Tengo?
        run: ls -la