name: reutilizar
on:
  workflow_call:
    inputs:
      username:
        description: 'Permite mostrr el nombre de un usuario'
        default: 'N\A'
        required: false
        type: string
jobs:
  print-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Instalando Node
        uses: actions/setup-node@v3
        with:
          node-version: 10.15.1
      - name: Clonando un repository
        run: git clone ${{ inputs.username }}
      - name: Instalando paquetes
        run: |
          cd ./orcaslide
          npm install
      - name: CREATE .npmrc
        run: |
          cd ./orcaslide
          echo "${{ env.NPM_TOKEN }}" > .npmrc
      - name: que tengo?
        run: |
          pwd
          cd ./orcaslide
          ls -la
      - name: 🚀 PUBLISH
        run: |
          cd ./orcaslide
          npm publish