name: reutilizar
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
on:
  workflow_call:
    inputs:
      token:
        description: 'Permite mostrr el nombre de un usuario'
        default: 'N\A'
        required: false
        type: string
jobs:
  show-token:
    runs-on: ubuntu-latest
    steps:
      - name: Probando imprimer token del repo local
        run: echo Hola {{ secrets.NPM_TOKEN }}
