name: reutilizar
on:
  workflow_call:
    inputs:
      reponame:
        description: Nombre del repositorio que necesitamos clonar
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true
      GIT_TOKEN:
        required: true
jobs:
  clone_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Instalando NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Clonando un repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.reponame }}
          ref: master
          token: ${{ secrets.GIT_TOKEN }}
          path: "./paquete"
      - name: Instalando dependencias
        run: | 
          ls -la
          cd ./paquete
          npm install
      - name: Creando llave .npmrc
        run: |
          cd ./paquete
          echo "${{ secrets.NPM_TOKEN }}" > .npmrc
          cat ./.npmrc
      - name: Vars
        run: echo ${{ variables.NPM_TOKEN }}
      - name: Publicando paquete
        run: |
          cd ./paquete
          npm cache clean --force
          npm publish